id: Microsoft ECM - Test
version: -1
name: Microsoft ECM - Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 14bf2f56-dbf2-455e-8141-1700a1ce2aa7
    type: start
    task:
      id: 14bf2f56-dbf2-455e-8141-1700a1ce2aa7
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 425a3843-5d5c-469f-83a6-862de109db2a
    type: regular
    task:
      id: 425a3843-5d5c-469f-83a6-862de109db2a
      version: -1
      name: Get Collections
      description: Gets a Configuration Manager collection
      script: Microsoft Endpoint Configuration Manager|||ms-ecm-collection-list
      type: regular
      iscommand: true
      brand: Microsoft Endpoint Configuration Manager
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      collection_id: {}
      collection_name:
        simple: All Systems
      collection_type:
        simple: Device
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 9b306d21-d111-4059-8131-e2b7b7a8b179
    type: regular
    task:
      id: 9b306d21-d111-4059-8131-e2b7b7a8b179
      version: -1
      name: Get Devices
      description: Gets a Configuration Manager device
      script: Microsoft Endpoint Configuration Manager|||ms-ecm-device-list
      type: regular
      iscommand: true
      brand: Microsoft Endpoint Configuration Manager
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      collection_id: {}
      collection_name: {}
      device_name:
        simple: EC2AMAZ-2AKQ815
      resource_id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 032a989d-afe2-44e0-837b-24509d8d279a
    type: regular
    task:
      id: 032a989d-afe2-44e0-837b-24509d8d279a
      version: -1
      name: Delete context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 8ef440fd-dabd-4376-84b4-923f5a925c6f
    type: condition
    task:
      id: 8ef440fd-dabd-4376-84b4-923f5a925c6f
      version: -1
      name: Validate collection ID
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: MicrosoftECM.Collections.ID
            iscontext: true
          right:
            value:
              simple: SMS00001
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: efe445eb-6360-4084-810c-f708465e04c9
    type: condition
    task:
      id: efe445eb-6360-4084-810c-f708465e04c9
      version: -1
      name: Validate Device
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualNumber
          left:
            value:
              simple: MicrosoftECM.Devices.ResourceID
            iscontext: true
          right:
            value:
              simple: "16777220"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 292aa269-a1e9-4662-815e-dbb5928b6e0d
    type: regular
    task:
      id: 292aa269-a1e9-4662-815e-dbb5928b6e0d
      version: -1
      name: Get Script
      description: Gets Configuration Manager PowerShell scripts
      script: Microsoft Endpoint Configuration Manager|||ms-ecm-script-list
      type: regular
      iscommand: true
      brand: Microsoft Endpoint Configuration Manager
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      author: {}
      script_name:
        simple: PSVersionTable
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: a890d262-9a2c-414e-83c9-d57597f16ffc
    type: condition
    task:
      id: a890d262-9a2c-414e-83c9-d57597f16ffc
      version: -1
      name: Is script exist
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: MicrosoftECM.Scripts.ScriptGuid
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 01c1a5a1-771a-4d53-8785-fbcd58d4c53b
    type: regular
    task:
      id: 01c1a5a1-771a-4d53-8785-fbcd58d4c53b
      version: -1
      name: Invoke-script
      description: Invokes a script in Configuration Manager
      script: Microsoft Endpoint Configuration Manager|||ms-ecm-script-invoke
      type: regular
      iscommand: true
      brand: Microsoft Endpoint Configuration Manager
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      collection_id: {}
      collection_name: {}
      device_name:
        simple: EC2AMAZ-2AKQ815
      script_guid:
        simple: ${MicrosoftECM.Scripts.ScriptGuid}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: f361b87d-fc76-4803-8f28-6f5145387309
    type: regular
    task:
      id: f361b87d-fc76-4803-8f28-6f5145387309
      version: -1
      name: Create script
      description: create new powershell script
      script: Microsoft Endpoint Configuration Manager|||ms-ecm-script-create
      type: regular
      iscommand: true
      brand: Microsoft Endpoint Configuration Manager
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      script_file_entry_id: {}
      script_name:
        simple: PSVersionTable
      script_text:
        simple: $PSVersionTable
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 8dcc53cc-e07d-456c-8232-0e54865c7395
    type: regular
    task:
      id: 8dcc53cc-e07d-456c-8232-0e54865c7395
      version: -1
      name: Approve script
      description: Approves a Configuration Manager PowerShell script
      script: Microsoft Endpoint Configuration Manager|||ms-ecm-script-approve
      type: regular
      iscommand: true
      brand: Microsoft Endpoint Configuration Manager
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      comment:
        simple: Approved
      script_guid:
        simple: ${MicrosoftECM.Scripts.ScriptGuid}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: ff3cf7c2-2d97-4626-8303-b4c7e34a8591
    type: regular
    task:
      id: ff3cf7c2-2d97-4626-8303-b4c7e34a8591
      version: -1
      name: Sleep
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      seconds:
        simple: "40"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: 7e6fd881-a632-4e6f-8264-0de2b84ecfc3
    type: regular
    task:
      id: 7e6fd881-a632-4e6f-8264-0de2b84ecfc3
      version: -1
      name: Get script invocation results
      description: Gets a script invocation results
      script: Microsoft Endpoint Configuration Manager|||ms-ecm-script-invocation-results
      type: regular
      iscommand: true
      brand: Microsoft Endpoint Configuration Manager
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      operation_id:
        simple: ${MicrosoftECM.ScriptsInvocation.OperationID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 81ac22d3-0ce4-49eb-894a-0b68118b1ec0
    type: condition
    task:
      id: 81ac22d3-0ce4-49eb-894a-0b68118b1ec0
      version: -1
      name: Validate script invocation results
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualNumber
          left:
            value:
              simple: MicrosoftECM.ScriptsInvocationResults.ScriptExitCode
            iscontext: true
          right:
            value:
              simple: "0"
      - - operator: isEqualString
          left:
            value:
              simple: MicrosoftECM.ScriptsInvocationResults.ScriptGuid
            iscontext: true
          right:
            value:
              simple: MicrosoftECM.Scripts.ScriptGuid
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 3e68b388-7ba3-420c-88ed-33979bd77a19
    type: regular
    task:
      id: 3e68b388-7ba3-420c-88ed-33979bd77a19
      version: -1
      name: Get Primary User
      description: Get the primary user of a given computer name
      script: Microsoft Endpoint Configuration Manager|||ms-ecm-user-get-primary
      type: regular
      iscommand: true
      brand: Microsoft Endpoint Configuration Manager
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      device_name:
        simple: EC2AMAZ-2AKQ815
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: 1bb72cc5-ea6c-4649-8aaf-b38351ed7f2b
    type: condition
    task:
      id: 1bb72cc5-ea6c-4649-8aaf-b38351ed7f2b
      version: -1
      name: Validate Primary User
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "16"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: MicrosoftECM.PrimaryUsers.MachineName
            iscontext: true
          right:
            value:
              simple: EC2AMAZ-2AKQ815
      - - operator: isEqualString
          left:
            value:
              simple: MicrosoftECM.PrimaryUsers.UserName
            iscontext: true
          right:
            value:
              simple: demisto\sccmadmin
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2645
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: b1d5e156-b2c7-4473-8b1d-b546c86a5acf
    type: regular
    task:
      id: b1d5e156-b2c7-4473-8b1d-b546c86a5acf
      version: -1
      name: Get Last Log On User
      description: Gets the last user that logged on to a given computer name
      script: Microsoft Endpoint Configuration Manager|||ms-ecm-user-last-log-on
      type: regular
      iscommand: true
      brand: Microsoft Endpoint Configuration Manager
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      device_name:
        simple: EC2AMAZ-2AKQ815
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: 2b908293-b251-4a99-80ef-4aded1d12872
    type: condition
    task:
      id: 2b908293-b251-4a99-80ef-4aded1d12872
      version: -1
      name: Validate Last Log On User
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "18"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: MicrosoftECM.LastLogOnUser.Name
            iscontext: true
          right:
            value:
              simple: EC2AMAZ-2AKQ815
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2995
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "18":
    id: "18"
    taskid: 332a35cb-7a08-465d-858e-d91d4ef6e902
    type: title
    task:
      id: 332a35cb-7a08-465d-858e-d91d4ef6e902
      version: -1
      name: Successful
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3185,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.5.0
description: This is a test playbook for the Microsoft Endpoint Configuration Manager
  integration
